name:                gpxTool
version:             0.1.0.0
github:              "waltont8/gpxTool"
license:             BSD3
author:              "Travis Walton"
maintainer:          "spam@example.com"
copyright:           "(c) 2019 waltont8"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/waltont8/gpxTool#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  gpxTool-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - gpxTool

tests:
  gpxTool-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - gpxTool
